[deploy]
build = { cmd = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_superuser.py" }
start = { cmd = "gunicorn franklin_used_rv.wsgi:application --bind 0.0.0.0:$PORT" }
