# Generated by Django 5.2.5 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada')], default='USA', max_length=20),
        ),
    ]
