# Generated by Django 5.2.5 on 2025-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='down_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=12, null=True),
        ),
    ]
